### ISSUE TITLE
Polygon 0 addresses as output

### ISSUE THREAD

**Issue by barkntuncer** [PatrickAlphaC/find-addresses-chainlink#1]
Hey Patrick! Barkin here from Nansen. Thank you for this script. I would love to point out some issues and request your feedback on one of the outputs :) 

Firstly, the `run_all.sh` and the `brownie-config.yaml` is not the same for Polygon. The second thing is actually a question. So, I have seen that the Multicall2 address for Polygon is actually Polygon's Multicall address. I have found Polygon's Multicall2 address [here](https://github.com/makerdao/multicall/pull/24/files) but it did not change the output, which is actually my last question. We are getting 0 addresses as output for the Polygon case. I have configured Infura for Polygon but is there something I am missing?  

Thank you in advance!
Barkin

**Comment by PatrickAlphaC** [comment]
Hello! I'm not actively maintaining this repo... sorry. 

...how did you find this repo?

**Comment by barkntuncer** [comment]
gm Patrick! My teammates told me that they have talked to you in Chainlink group and you created this repo for them. As a reminder, I am from Nansen 😄

**Comment by PatrickAlphaC** [comment]
Might be a bug :/ 

Sorry, I'm a little light on time right now, not sure I'll have time to debug this.

**Comment by barkntuncer** [comment]
Alright! No worries. Thank you very much!
